import type { Timestamp } from './firestore';

export interface LocalizedText {
  en: string;
  ja: string;
}

export interface ParsedHours {
  /** Raw string from 88onsen.com — the canonical fallback / "original text" */
  raw: string;
  /** Structured base weekly schedule, or null when the hours can't be a clean grid */
  schedule: WeeklySchedule | null;
  /**
   * Display-only caveats shown under the grid (seasonal hours, monthly Nth-weekday
   * closures, holiday rules, irregular closing, split sessions). The app renders
   * these as captions; it never computes open/closed from them.
   */
  exceptions?: LocalizedText[];
  /** Parse confidence; anything other than 'high' surfaces a "hours may vary" hint. */
  confidence?: 'high' | 'medium' | 'low';
}

export interface WeeklySchedule {
  monday: DaySchedule | null;
  tuesday: DaySchedule | null;
  wednesday: DaySchedule | null;
  thursday: DaySchedule | null;
  friday: DaySchedule | null;
  saturday: DaySchedule | null;
  sunday: DaySchedule | null;
}

export interface DaySchedule {
  opens: string; // "HH:MM"
  closes: string; // "HH:MM"
}

/**
 * /onsens/{kyuhachiId}
 *
 * Onsen documents are never deleted. Deprecated onsens get isActive: false.
 * The kyuhachiId is a stable UUID assigned once by the data repo and never changes.
 */
export interface OnsenDocument {
  name: string;
  /**
   * Hiragana reading (yomi) of `name`, generated by the data-repo pipeline's
   * morphological analyzer. Used as the within-prefecture sort key so the list
   * orders by reading (gojūon) rather than by the kanji code points of `name`,
   * which is effectively arbitrary to a reader. Must be normalized to hiragana
   * (hiragana is laid out in gojūon order in Unicode, so a plain code-point sort
   * is correct and needs no locale collation). null until the catalog publishes
   * it, or when the analyzer produces no reading — the app falls back to `name`.
   */
  nameKana: string | null;
  /**
   * Hepburn romanization (rōmaji) of `name`, derived by the data-repo pipeline
   * from the same reading as `nameKana`. A pronunciation aid: the app shows it
   * beneath the kanji name for users whose UI language is not Japanese, so a
   * non-Japanese reader can pronounce and search the onsen. Never a translation
   * — the kanji `name` is always the primary display. null until the catalog
   * publishes it, or when the analyzer produces no reading — the app then shows
   * the kanji alone.
   */
  nameRomaji: string | null;
  areaName: string;
  /**
   * Stable UUID of the coarse tourist region this onsen rolls up into, joining
   * it to /area_guides/{areaId}. The data repo owns how areaNames group into
   * regions and assigns the id. null until the data repo publishes it; the app
   * then shows no area guide for the onsen.
   */
  areaId: string | null;
  address: string;
  prefecture: string;
  lat: number;
  lng: number;
  phone: string | null;
  businessHours: ParsedHours | null;
  admissionFee: string | null;
  /** Adult weekday walk-in admission in yen; null if no parseable individual fee. Derived from admissionFee by the data repo. */
  adultFee: number | null;
  springQuality: string | null;
  websiteUrl: string | null;
  imageUrl: string | null;
  /** BlurHash of imageUrl, shown as an instant placeholder while the photo loads. Published by the data repo alongside imageUrl. */
  blurhash: string | null;
  /** false = deprecated; never deleted from Firestore */
  isActive: boolean;
  catalogVersion: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * /catalog_meta/current
 *
 * Written atomically by the data repo publish script.
 * The app reads this on startup to check for catalog updates.
 */
export interface CatalogMetaDocument {
  version: number;
  publishedAt: Timestamp;
  totalCount: number;
  activeCount: number;
}

/**
 * One onsen as stored in the device's offline catalog cache: the Firestore
 * document minus its Timestamps (not JSON-serializable, and no screen reads
 * them), plus its document id (the kyuhachiId).
 */
export type CachedOnsen = Omit<OnsenDocument, 'createdAt' | 'updatedAt'> & {
  id: string;
};

/**
 * The device-local snapshot of the published onsen catalog, persisted as a
 * single JSON blob. `version` mirrors /catalog_meta/current.version at fetch
 * time and is the sole freshness signal: the cache is replaced whole when the
 * published version moves past it, never patched incrementally. Includes every
 * onsen ever published — active and archived — since challenge snapshots can
 * reference onsens that were later deprecated.
 */
export interface CachedCatalog {
  version: number;
  /** Epoch ms when the device stored this snapshot. Diagnostics only. */
  fetchedAt: number;
  onsens: CachedOnsen[];
}
