import type { Timestamp } from './firestore';

export interface LocalizedText {
  en: string;
  ja: string;
}

export interface ParsedHours {
  /** Raw string from 88onsen.com, the canonical fallback / "original text" */
  raw: string;
  /** Structured base weekly schedule, or null when the hours can't be a clean grid */
  schedule: WeeklySchedule | null;
  /**
   * Display-only caveats shown under the grid (seasonal hours, monthly Nth-weekday
   * closures, holiday rules, irregular closing, split sessions). The app renders
   * these as captions; it never computes open/closed from them.
   */
  exceptions?: LocalizedText[];
  /** Parse confidence; anything other than 'high' surfaces a "hours may vary" hint. */
  confidence?: 'high' | 'medium' | 'low';
}

export interface WeeklySchedule {
  monday: DaySchedule | null;
  tuesday: DaySchedule | null;
  wednesday: DaySchedule | null;
  thursday: DaySchedule | null;
  friday: DaySchedule | null;
  saturday: DaySchedule | null;
  sunday: DaySchedule | null;
}

export interface DaySchedule {
  opens: string; // "HH:MM"
  closes: string; // "HH:MM"
}

/**
 * /onsens/{kyuhachiId}
 *
 * Onsen documents are never deleted. Deprecated onsens get isActive: false.
 * The kyuhachiId is a stable UUID assigned once by the data repo and never changes.
 */
export interface OnsenDocument {
  name: string;
  /**
   * Hiragana reading (yomi) of `name`, generated by the data-repo pipeline's
   * morphological analyzer. Used as the within-prefecture sort key so the list
   * orders by reading (gojūon) rather than by the kanji code points of `name`,
   * which is effectively arbitrary to a reader. Must be normalized to hiragana
   * (hiragana is laid out in gojūon order in Unicode, so a plain code-point sort
   * is correct and needs no locale collation). null until the catalog publishes
   * it, or when the analyzer produces no reading; the app falls back to `name`.
   */
  nameKana: string | null;
  /**
   * Hepburn romanization (rōmaji) of `name`, derived by the data-repo pipeline
   * from the same reading as `nameKana`. A pronunciation aid: the app shows it
   * beneath the kanji name for users whose UI language is not Japanese, so a
   * non-Japanese reader can pronounce and search the onsen. Never a translation:
   * the kanji `name` is always the primary display. null until the catalog
   * publishes it, or when the analyzer produces no reading; the app then shows
   * the kanji alone.
   */
  nameRomaji: string | null;
  areaName: string;
  /**
   * Stable UUID of the coarse tourist region this onsen rolls up into, joining
   * it to /area_guides/{areaId}. The data repo owns how areaNames group into
   * regions and assigns the id. null until the data repo publishes it; the app
   * then shows no area guide for the onsen.
   */
  areaId: string | null;
  address: string;
  prefecture: string;
  lat: number;
  lng: number;
  phone: string | null;
  businessHours: ParsedHours | null;
  admissionFee: string | null;
  /** Adult weekday walk-in admission in yen; null if no parseable individual fee. Derived from admissionFee by the data repo. */
  adultFee: number | null;
  springQuality: string | null;
  websiteUrl: string | null;
  /**
   * The onsen's page on 88onsen.com, the source of `imageUrl`. Published so the
   * app can credit each catalog photo back to where it came from: the licence
   * granted by 九州観光機構 on 2026-08-31 was requested on the terms of per-photo
   * credit plus a link back, and the app never sees the upstream id the URL is
   * built from. This is the photo's attribution target, not a general "more
   * info" link; `websiteUrl` is the facility's own site.
   *
   * null on any doc published before the data repo backfilled it, so the credit
   * has to render as plain text when it's missing rather than assuming a link.
   */
  detailPageUrl: string | null;
  imageUrl: string | null;
  /** BlurHash of imageUrl, shown as an instant placeholder while the photo loads. Published by the data repo alongside imageUrl. */
  blurhash: string | null;
  /** false = deprecated; never deleted from Firestore */
  isActive: boolean;
  /**
   * When the data repo last re-checked this onsen against 88onsen.com, whether
   * or not anything changed (unlike `updatedAt`, which only moves on a real
   * edit). Diagnostics for the data repo; nothing in the app or the website
   * reads it. Published on every document since the pipeline started stamping
   * it, so it is declared here rather than left as undeclared drift.
   */
  dataVerifiedAt: Timestamp;
  catalogVersion: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * /catalog_meta/current
 *
 * Written atomically by the data repo publish script.
 * The app reads this on startup to check for catalog updates.
 */
export interface CatalogMetaDocument {
  version: number;
  publishedAt: Timestamp;
  totalCount: number;
  activeCount: number;
}

/** Current packing of `CatalogIndexDocument.entries`. See the document type. */
export const CATALOG_INDEX_SCHEMA_VERSION = 1;

/**
 * One onsen inside the packed `CatalogIndexDocument.entries` string: a
 * positional tuple, not an object, because a key repeated 161 times is the
 * cost this document exists to avoid.
 *
 * Positional means the order is the contract. A reader indexes by position, so
 * a later schema may APPEND a field without breaking anything; reordering or
 * removing one is a breaking change and must bump
 * CATALOG_INDEX_SCHEMA_VERSION.
 */
export type CatalogIndexEntry = [
  /** The kyuhachiId, i.e. the /onsens document id. */
  id: string,
  name: string,
  nameRomaji: string | null,
  areaName: string,
  prefecture: string,
  /** Published rounded to 5 decimal places (~1.1 m), as tracks are. */
  lat: number,
  lng: number,
];

/**
 * /catalog_index/current
 *
 * A slim, derived projection of the onsen catalog for the public journey
 * website, published atomically by the data repo alongside /onsens and
 * /catalog_meta. Derived: /onsens stays the source of truth and keeps every
 * field, because the app reads and uses nearly all of them.
 *
 * Why it exists. The website joins onsens onto a map and needs seven values
 * per onsen; reading /onsens to get them cost 386 KB (62 KB gzipped) across
 * 161 documents on every page load, because Firestore wraps every field of
 * every document in protobuf-JSON and `businessHours` alone accounted for
 * 130 KB of what was downloaded and never read. This document carries the same
 * 161 onsens in 24 KB (11 KB gzipped), in one document read. Same trade as the
 * encoded polyline on /journey_days: per-item structural overhead dominates,
 * so pack the payload. Measured against production on 2026-09-07; see
 * docs/adr/012-website-catalog-index.md.
 *
 * Entries cover EVERY onsen, active and archived alike. The site has to be
 * able to place a visit to an onsen that was later deprecated, and a frozen
 * challenge snapshot may still name one, so filtering on isActive here would
 * lose dots the map has to draw. `isActive` itself is absent because nothing
 * on the site branches on it.
 *
 * Size: 24 KB against Firestore's 1 MiB per-document limit, i.e. room for
 * roughly 40x the current catalog. Nothing here needs to page.
 */
export interface CatalogIndexDocument {
  /**
   * How `entries` is packed, currently CATALOG_INDEX_SCHEMA_VERSION. A reader
   * that does not recognise the value must treat the whole document as
   * unusable rather than guess at the packing.
   */
  schemaVersion: number;
  /** The catalog this was derived from: mirrors /catalog_meta/current.version. */
  version: number;
  publishedAt: Timestamp;
  /** Number of entries, for verifying a publish; the site does not gate on it. */
  count: number;
  /**
   * JSON.stringify of a CatalogIndexEntry[], stored as one string rather than
   * as a native Firestore array. That is the whole point of the document: a
   * native array of maps re-incurs the per-value protobuf-JSON overhead this
   * exists to remove, and measured 54 KB against this shape's 24 KB.
   */
  entries: string;
}

/**
 * One onsen as stored in the device's offline catalog cache: the Firestore
 * document minus its Timestamps (not JSON-serializable, and no screen reads
 * them), plus its document id (the kyuhachiId).
 */
export type CachedOnsen = Omit<
  OnsenDocument,
  'createdAt' | 'updatedAt' | 'dataVerifiedAt'
> & {
  id: string;
};

/**
 * The device-local snapshot of the published onsen catalog, persisted as a
 * single JSON blob. `version` mirrors /catalog_meta/current.version at fetch
 * time and is the sole freshness signal: the cache is replaced whole when the
 * published version moves past it, never patched incrementally. Includes every
 * onsen ever published (active and archived) since challenge snapshots can
 * reference onsens that were later deprecated.
 */
export interface CachedCatalog {
  version: number;
  /** Epoch ms when the device stored this snapshot. Diagnostics only. */
  fetchedAt: number;
  onsens: CachedOnsen[];
}
