import type { Timestamp } from './firestore';

export interface LocalizedText {
  en: string;
  ja: string;
}

export interface ParsedHours {
  /** Raw string from 88onsen.com — the canonical fallback / "original text" */
  raw: string;
  /** Structured base weekly schedule, or null when the hours can't be a clean grid */
  schedule: WeeklySchedule | null;
  /**
   * Display-only caveats shown under the grid (seasonal hours, monthly Nth-weekday
   * closures, holiday rules, irregular closing, split sessions). The app renders
   * these as captions; it never computes open/closed from them.
   */
  exceptions?: LocalizedText[];
  /** Parse confidence; anything other than 'high' surfaces a "hours may vary" hint. */
  confidence?: 'high' | 'medium' | 'low';
}

export interface WeeklySchedule {
  monday: DaySchedule | null;
  tuesday: DaySchedule | null;
  wednesday: DaySchedule | null;
  thursday: DaySchedule | null;
  friday: DaySchedule | null;
  saturday: DaySchedule | null;
  sunday: DaySchedule | null;
}

export interface DaySchedule {
  opens: string; // "HH:MM"
  closes: string; // "HH:MM"
}

/**
 * /onsens/{kyuhachiId}
 *
 * Onsen documents are never deleted. Deprecated onsens get isActive: false.
 * The kyuhachiId is a stable UUID assigned once by the data repo and never changes.
 */
export interface OnsenDocument {
  name: string;
  /**
   * Hiragana reading (yomi) of `name`, generated by the data-repo pipeline's
   * morphological analyzer. Used as the within-prefecture sort key so the list
   * orders by reading (gojūon) rather than by the kanji code points of `name`,
   * which is effectively arbitrary to a reader. Must be normalized to hiragana
   * (hiragana is laid out in gojūon order in Unicode, so a plain code-point sort
   * is correct and needs no locale collation). null until the catalog publishes
   * it, or when the analyzer produces no reading — the app falls back to `name`.
   */
  nameKana: string | null;
  areaName: string;
  address: string;
  prefecture: string;
  lat: number;
  lng: number;
  phone: string | null;
  businessHours: ParsedHours | null;
  admissionFee: string | null;
  /** Adult weekday walk-in admission in yen; null if no parseable individual fee. Derived from admissionFee by the data repo. */
  adultFee: number | null;
  springQuality: string | null;
  websiteUrl: string | null;
  imageUrl: string | null;
  /** BlurHash of imageUrl, shown as an instant placeholder while the photo loads. Published by the data repo alongside imageUrl. */
  blurhash: string | null;
  /** false = deprecated; never deleted from Firestore */
  isActive: boolean;
  catalogVersion: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

/**
 * /catalog_meta/current
 *
 * Written atomically by the data repo publish script.
 * The app reads this on startup to check for catalog updates.
 */
export interface CatalogMetaDocument {
  version: number;
  publishedAt: Timestamp;
  totalCount: number;
  activeCount: number;
}
